development:
  adapter: postgresql
  encoding: unicode
  database: streetmix_development
  pool: 5
  username: drew
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: streetmix_test
  pool: 5
  username: drew
  password:
